# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Must Haves"
email: info@piparadox.live
description: "Question Papers and Cheat Sheets"
baseurl: "/must-haves"
url: "https://mathinfo.piparadox.live"
twitter_username: 
github_username:  
color_theme:  "#000000"
color_text:  "#000"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
